### PR TITLE
Update to 0.5.1

### PR DESCRIPTION
**Pull request by whcemyesil**

### CODE REVIEW

**Comment by whcemyesil** [comment]
@mathaeus 
@fabb 

pls review. 0.5.1 was released for xcode 10

**Review by mathaeus — APPROVED** [review]

**Comment by fabb** [comment]
fyi i also updated our `master` branch to the one from `upstream` (i know it's not necessary, but looks cleaner when not having added the upstream repo as remote)

**Comment by fabb** [comment]
so the main update in this version is an update of the subdependencies, right? have you looked through the release notes of the subdependencies, if there is something we should be aware of?

**Comment by whcemyesil** [comment]
> so the main update in this version is an update of the subdependencies, right? have you looked through the release notes of the subdependencies, if there is something we should be aware of?

we're not using the subdependencies (dfp & mopub sdk)
this update is mainly for xcode 10 support

**Comment by fabb** [comment]
google ads sdk was also updated:
```
  - Google-Mobile-Ads-SDK (7.30.0)
  + Google-Mobile-Ads-SDK (7.34.0)
```

**Comment by fabb** [comment]
ah forget it 🤦‍♂️ the changes were just in the demo project...

**Review by fabb — APPROVED** [review]

**Comment by mathaeus** [comment]
@fabb I was about to ask the same and in the very last second saw that it’s the demo project. 😅

**Pull request merged**
